//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Game Development Process_A864547_a864547_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_-rGXcWPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Create Release_9BE012C5_7003bf42_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_-rGXcWPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Create Release_9BE012C5_7003bf42_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_9tL9smPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_D9954CBD_adb8f93a_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_9tL9smPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_D9954CBD_adb8f93a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Post-Production_BBC9A8E_62adc929_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_wwch0WPREemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Design_B73C13C4_73726c5a_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_wwch0WPREemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Design_B73C13C4_73726c5a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMSmPTEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Plan Production_8B7B6E21_edc250aa_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMSmPTEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Plan Production_8B7B6E21_edc250aa_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_6-IWcmPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Testing_E18BD5AA_b5af8227_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_6-IWcmPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Testing_E18BD5AA_b5af8227_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_ECokMWPSEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Architecture_C502FBFD_81395493_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_ECokMWPSEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Architecture_C502FBFD_81395493_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_kCzVEWPSEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Plan Production_AD47CFDF_697e2875_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_kCzVEWPSEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Plan Production_AD47CFDF_697e2875_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_dqIbcmPVEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Perform Game Demo_9662320C_6a85de89_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_dqIbcmPVEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Perform Game Demo_9662320C_6a85de89_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_ZD0-sWPVEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Perform Game Demo_45B6A1C7_a7fd8450_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_ZD0-sWPVEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Perform Game Demo_45B6A1C7_a7fd8450_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Production_F04A349A_473b6335_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Pre-Production_8F5CC1A7_e64df042_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Pre-Production_8F5CC1A7_e64df042_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMSGPTEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Architecture_924479FB_f48b5c84_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMSGPTEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Architecture_924479FB_f48b5c84_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_czXA8WPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Implementation_43CC951A_a61377a3_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_czXA8WPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Implementation_43CC951A_a61377a3_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_k0dJkWPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Testing_1366FB32_75adddbb_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_k0dJkWPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Testing_1366FB32_75adddbb_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_u9sVUWPSEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_6438C862_206f20f8_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,_u9sVUWPSEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_6438C862_206f20f8_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_3tEOUWPUEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Defect Fixing_11F8E348_e61c8fc5_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_3tEOUWPUEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Defect Fixing_11F8E348_e61c8fc5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,__05_gWPREemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Art and Interface_FD8C1DE3_b9c27679_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_irjgMWPQEemIdoc4rfIcVg,__05_gWPREemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Art and Interface_FD8C1DE3_b9c27679_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMRGPTEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Design_CDB297DC_2ff97a65_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMRGPTEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Identify and Refine Game Design_CDB297DC_2ff97a65_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMTGPTEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_56D65C1A_b91d3ea3_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_q-OEgWPREemIdoc4rfIcVg,_-TgMTGPTEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Create Presentation_56D65C1A_b91d3ea3_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_Hd0KQWPVEemIdoc4rfIcVgActivity"]="./../../Game Development Process/deliveryprocesses/resources/Perform Project Postmortem_62059F39_36294bb6_Activity.jpeg"
contentPage.processPage.imageFiles["_dDRpEWPQEemIdoc4rfIcVg,_sogRgWPQEemIdoc4rfIcVg,_Hd0KQWPVEemIdoc4rfIcVgActivityDetail"]="./../../Game Development Process/deliveryprocesses/resources/Perform Project Postmortem_62059F39_36294bb6_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_FSPKw2YeEemzSZdddslyvQ"] = ["Professor","Game Development Process/deliveryprocesses/professor_835BA379.html"];
contentPage.processPage.elementUrls["_InGNtmYeEemzSZdddslyvQ"] = ["UI Mockups","Game Development Process/deliveryprocesses/ui_mockups_F8CDD7BB.html"];
contentPage.processPage.elementUrls["_88pngGYXEemzSZdddslyvQ"] = ["Create and Update Game Design Document","Game Development Process/deliveryprocesses/create_and_update_game_design_document_AB1C6247.html"];
contentPage.processPage.elementUrls["_NPU1oWblEemO0uSCmyE9oA"] = ["Artist","Game Development Process/deliveryprocesses/artist_AE77AC38.html"];
contentPage.processPage.elementUrls["_of66EGYWEemzSZdddslyvQ"] = ["Create UI Mockups","Game Development Process/deliveryprocesses/create_ui_mockups_E8283181.html"];
contentPage.processPage.elementUrls["_aIcr92YbEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_128D8663.html"];
contentPage.processPage.elementUrls["_xLClMWYYEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_635F1911.html"];
contentPage.processPage.elementUrls["_xKNh_WYcEemzSZdddslyvQ"] = ["Project Plan and Schedule","Game Development Process/deliveryprocesses/project_plan_and_schedule_68E4DF59.html"];
contentPage.processPage.elementUrls["_MTExUGb8EemO0uSCmyE9oA"] = ["Game","Game Development Process/deliveryprocesses/game_A87911CA.html"];
contentPage.processPage.elementUrls["_xKIpd2YcEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_7E5B11FC.html"];
contentPage.processPage.elementUrls["_-rGXcWPUEemIdoc4rfIcVg"] = ["Create Release","Game Development Process/deliveryprocesses/Create Release_9BE012C5.html"];
contentPage.processPage.elementUrls["_mh3R8GYWEemzSZdddslyvQ"] = ["Create and Update State Diagram","Game Development Process/deliveryprocesses/create_and_update_state_diagram_C0A359B1.html"];
contentPage.processPage.elementUrls["_xKEYAWYcEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_2E201C11.html"];
contentPage.processPage.elementUrls["_FSBIQmYeEemzSZdddslyvQ"] = ["Test Plan","Game Development Process/deliveryprocesses/test_plan_A6ABC066.html"];
contentPage.processPage.elementUrls["_C___KWYaEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_A2CDB81A.html"];
contentPage.processPage.elementUrls["_HsKwIGYWEemzSZdddslyvQ"] = ["Create and Update Game Design Document","Game Development Process/deliveryprocesses/create_and_update_game_design_document_585E2B1D.html"];
contentPage.processPage.elementUrls["_o9vT9WYVEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_2D9DF28D.html"];
contentPage.processPage.elementUrls["_NPLrt2blEemO0uSCmyE9oA"] = ["Tester","Game Development Process/deliveryprocesses/tester_F0564958.html"];
contentPage.processPage.elementUrls["_iC2MIGYaEemzSZdddslyvQ"] = ["Game Concept","Game Development Process/deliveryprocesses/game_concept_78BD5F05.html"];
contentPage.processPage.elementUrls["_j4m-cWYbEemzSZdddslyvQ"] = ["Object Oriented Design","Game Development Process/deliveryprocesses/object_oriented_design_4A972851.html"];
contentPage.processPage.elementUrls["_aIfIOmYbEemzSZdddslyvQ"] = ["Class Diagram","Game Development Process/deliveryprocesses/class_diagram_54D8FA7C.html"];
contentPage.processPage.elementUrls["_xLppMWYYEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_517B4EC8.html"];
contentPage.processPage.elementUrls["_hyAW9GYeEemzSZdddslyvQ"] = ["Code Repository","Game Development Process/deliveryprocesses/code_repository_53EE55CB.html"];
contentPage.processPage.elementUrls["_GoMYZGYbEemzSZdddslyvQ"] = ["UI Mockups","Game Development Process/deliveryprocesses/ui_mockups_3EDE6774.html"];
contentPage.processPage.elementUrls["_yuU2pWb5EemO0uSCmyE9oA"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_5D21F07B.html"];
contentPage.processPage.elementUrls["_xK6CUWYYEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_C7D3A9CC.html"];
contentPage.processPage.elementUrls["_ECokMWPSEemIdoc4rfIcVg"] = ["Identify and Refine Game Architecture","Game Development Process/deliveryprocesses/Identify and Refine Architecture_C502FBFD.html"];
contentPage.processPage.elementUrls["_NrspoGYWEemzSZdddslyvQ"] = ["Create and Update Object Oreintated Design","Game Development Process/deliveryprocesses/create_and_update_object_oreintated_design_322FF881.html"];
contentPage.processPage.elementUrls["_fEx1UGYWEemzSZdddslyvQ"] = ["Create Release Notes","Game Development Process/deliveryprocesses/create_release_notes_8A4079F2.html"];
contentPage.processPage.elementUrls["_9hPXwGYWEemzSZdddslyvQ"] = ["Game Demo","Game Development Process/deliveryprocesses/game_demo_DCB3AA4F.html"];
contentPage.processPage.elementUrls["_3tEOUWPUEemIdoc4rfIcVg"] = ["Defect Fixing","Game Development Process/deliveryprocesses/Defect Fixing_11F8E348.html"];
contentPage.processPage.elementUrls["_NPLrwGblEemO0uSCmyE9oA"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_DBFB25CA.html"];
contentPage.processPage.elementUrls["_HrpBIGYVEemzSZdddslyvQ"] = ["Perform Test","Game Development Process/deliveryprocesses/perform_test_D8078A21.html"];
contentPage.processPage.elementUrls["_C_54gWYaEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_9696DC7D.html"];
contentPage.processPage.elementUrls["_xKNh9GYcEemzSZdddslyvQ"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_309F6EAF.html"];
contentPage.processPage.elementUrls["_0M-7Emb7EemO0uSCmyE9oA"] = ["Game Assets","Game Development Process/deliveryprocesses/game_assets_79F2B44C.html"];
contentPage.processPage.elementUrls["__JrVMGYWEemzSZdddslyvQ"] = ["Implement Game Play","Game Development Process/deliveryprocesses/implement_game_play_42DB34D1.html"];
contentPage.processPage.elementUrls["_czXA8WPUEemIdoc4rfIcVg"] = ["Implementation","Game Development Process/deliveryprocesses/Implementation_43CC951A.html"];
contentPage.processPage.elementUrls["_GOi7kGYWEemzSZdddslyvQ"] = ["Create Concept Art","Game Development Process/deliveryprocesses/create_concept_art_E214A15A.html"];
contentPage.processPage.elementUrls["_o9vT92YVEemzSZdddslyvQ"] = ["Source Code","Game Development Process/deliveryprocesses/source_code_8510DC68.html"];
contentPage.processPage.elementUrls["__44yUWYbEemzSZdddslyvQ"] = ["Meeting Log","Game Development Process/deliveryprocesses/meeting_log_3E6A0FEF.html"];
contentPage.processPage.elementUrls["_Nisuh2buEemO0uSCmyE9oA"] = ["Tester","Game Development Process/deliveryprocesses/tester_CFCD3382.html"];
contentPage.processPage.elementUrls["_FSIdB2YeEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_915E824E.html"];
contentPage.processPage.elementUrls["_xKM64WYcEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_517AF613.html"];
contentPage.processPage.elementUrls["_yuU2p2b5EemO0uSCmyE9oA"] = ["Code Repository","Game Development Process/deliveryprocesses/code_repository_B494DA56.html"];
contentPage.processPage.elementUrls["_uTrzAGYXEemzSZdddslyvQ"] = ["Create and Update Object Oreintated Design","Game Development Process/deliveryprocesses/create_and_update_object_oreintated_design_5F4D6576.html"];
contentPage.processPage.elementUrls["_NPLrtGblEemO0uSCmyE9oA"] = ["Source Code","Game Development Process/deliveryprocesses/source_code_8E457F6D.html"];
contentPage.processPage.elementUrls["_6OUcOmYbEemzSZdddslyvQ"] = ["Professor","Game Development Process/deliveryprocesses/professor_89871418.html"];
contentPage.processPage.elementUrls["_aIfINGYbEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_97102437.html"];
contentPage.processPage.elementUrls["_xKEYDWYcEemzSZdddslyvQ"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_7BD5C26E.html"];
contentPage.processPage.elementUrls["_NPU1pGblEemO0uSCmyE9oA"] = ["Developer","Game Development Process/deliveryprocesses/developer_686BAE47.html"];
contentPage.processPage.elementUrls["_FSPKumYeEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_915E0976.html"];
contentPage.processPage.elementUrls["_-TgMSGPTEemIdoc4rfIcVg"] = ["Identify and Refine Game Architecture","Game Development Process/deliveryprocesses/Identify and Refine Architecture_924479FB.html"];
contentPage.processPage.elementUrls["_0M-7EWb7EemO0uSCmyE9oA"] = ["Class Diagram","Game Development Process/deliveryprocesses/class_diagram_8B59A036.html"];
contentPage.processPage.elementUrls["_u9sVUWPSEemIdoc4rfIcVg"] = ["Create Presentation","Game Development Process/deliveryprocesses/Create Presentation_6438C862.html"];
contentPage.processPage.elementUrls["_CWz-wGPWEemIdoc4rfIcVg"] = ["Milestone 4","Game Development Process/deliveryprocesses/Milestone 4_755A2034.html"];
contentPage.processPage.elementUrls["_NPU1qmblEemO0uSCmyE9oA"] = ["Tester","Game Development Process/deliveryprocesses/tester_2634848C.html"];
contentPage.processPage.elementUrls["_vjqs0WYaEemzSZdddslyvQ"] = ["Game Assets","Game Development Process/deliveryprocesses/game_assets_99524ECF.html"];
contentPage.processPage.elementUrls["_aIcr-mYbEemzSZdddslyvQ"] = ["Class Diagram","Game Development Process/deliveryprocesses/class_diagram_72DD172A.html"];
contentPage.processPage.elementUrls["_R-WKkGYWEemzSZdddslyvQ"] = ["Create Presentations","Game Development Process/deliveryprocesses/create_presentation_C5719B73.html"];
contentPage.processPage.elementUrls["_iCzI0WYaEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_3FF6EDC2.html"];
contentPage.processPage.elementUrls["_q-OEgWPREemIdoc4rfIcVg"] = ["Production","Game Development Process/deliveryprocesses/Production_F04A349A.html"];
contentPage.processPage.elementUrls["_o9vT8WYVEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_690C106E.html"];
contentPage.processPage.elementUrls["_kCzVEWPSEemIdoc4rfIcVg"] = ["Plan and Schedule","Game Development Process/deliveryprocesses/Plan Production_AD47CFDF.html"];
contentPage.processPage.elementUrls["_NPLrw2blEemO0uSCmyE9oA"] = ["Code Repository","Game Development Process/deliveryprocesses/code_repository_3E0BEFB5.html"];
contentPage.processPage.elementUrls["_InGNsmYeEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_343BF59C.html"];
contentPage.processPage.elementUrls["_FSPKvWYeEemzSZdddslyvQ"] = ["Game","Game Development Process/deliveryprocesses/game_6756D77F.html"];
contentPage.processPage.elementUrls["_xKNh-mYcEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_F2FFC961.html"];
contentPage.processPage.elementUrls["_iCyhwWYaEemzSZdddslyvQ"] = ["Game Concept","Game Development Process/deliveryprocesses/game_concept_C46CA45B.html"];
contentPage.processPage.elementUrls["_xKJQhGYcEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_2E91D08D.html"];
contentPage.processPage.elementUrls["_WQ8BIGYWEemzSZdddslyvQ"] = ["Setup Github Repository","Game Development Process/deliveryprocesses/setup_github_repository_C89A594A.html"];
contentPage.processPage.elementUrls["__9n6oGYWEemzSZdddslyvQ"] = ["Implement Tool Builder, Level or Map Editor","Game Development Process/deliveryprocesses/implement_tool_builder_level_or_map_editor_343F5DC2.html"];
contentPage.processPage.elementUrls["_xKE_EWYcEemzSZdddslyvQ"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_1265EF13.html"];
contentPage.processPage.elementUrls["_FSPKsWYeEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_19A13122.html"];
contentPage.processPage.elementUrls["_NPU1rWblEemO0uSCmyE9oA"] = ["Project Postmortem","Game Development Process/deliveryprocesses/project_postmortem_FC2D5295.html"];
contentPage.processPage.elementUrls["_9tL9smPUEemIdoc4rfIcVg"] = ["Create Presentation","Game Development Process/deliveryprocesses/Create Presentation_D9954CBD.html"];
contentPage.processPage.elementUrls["_NisuiWbuEemO0uSCmyE9oA"] = ["Game Concept","Game Development Process/deliveryprocesses/game_concept_3CEC2BC6.html"];
contentPage.processPage.elementUrls["_eA12oGYXEemzSZdddslyvQ"] = ["Game Demo","Game Development Process/deliveryprocesses/game_demo_B1CB381E.html"];
contentPage.processPage.elementUrls["_0NIsEWb7EemO0uSCmyE9oA"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_2194F157.html"];
contentPage.processPage.elementUrls["_AhgqAGPWEemIdoc4rfIcVg"] = ["Milestone 2","Game Development Process/deliveryprocesses/Milestone 2_37F05434.html"];
contentPage.processPage.elementUrls["_59UagGYVEemzSZdddslyvQ"] = ["Choose External Tool and Technologies","Game Development Process/deliveryprocesses/choose_external_tool_and_technologies_90B4C097.html"];
contentPage.processPage.elementUrls["_kB5-IWb8EemO0uSCmyE9oA"] = ["Meeting Log","Game Development Process/deliveryprocesses/meeting_log_A222EA7B.html"];
contentPage.processPage.elementUrls["_o9vT8GYVEemzSZdddslyvQ"] = ["Charater and Object Implmentation","Game Development Process/deliveryprocesses/charater_and_object_implmentation_5E6E305E.html"];
contentPage.processPage.elementUrls["_xKJQimYcEemzSZdddslyvQ"] = ["Project Plan and Schedule","Game Development Process/deliveryprocesses/project_plan_and_schedule_EC5AA6D2.html"];
contentPage.processPage.elementUrls["_0M1xIGb7EemO0uSCmyE9oA"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_69CD741F.html"];
contentPage.processPage.elementUrls["_aIcr8WYbEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_F688BA69.html"];
contentPage.processPage.elementUrls["_0NIsEGb7EemO0uSCmyE9oA"] = ["Object Oriented Design","Game Development Process/deliveryprocesses/object_oriented_design_16F71147.html"];
contentPage.processPage.elementUrls["_k0dJkWPUEemIdoc4rfIcVg"] = ["Testing","Game Development Process/deliveryprocesses/Testing_1366FB32.html"];
contentPage.processPage.elementUrls["_SCH9sWYeEemzSZdddslyvQ"] = ["Test Reults","Game Development Process/deliveryprocesses/test_reults_71D2C09B.html"];
contentPage.processPage.elementUrls["_NPU1p2blEemO0uSCmyE9oA"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_CA7C7832.html"];
contentPage.processPage.elementUrls["_6SNP8GYWEemzSZdddslyvQ"] = ["Finalize Basic Game Algorithim","Game Development Process/deliveryprocesses/finalize_basic_game_algorithim_A418F676.html"];
contentPage.processPage.elementUrls["_-TgMTGPTEemIdoc4rfIcVg"] = ["Create Presentation","Game Development Process/deliveryprocesses/Create Presentation_56D65C1A.html"];
contentPage.processPage.elementUrls["_NisugWbuEemO0uSCmyE9oA"] = ["Artist","Game Development Process/deliveryprocesses/artist_B3C86788.html"];
contentPage.processPage.elementUrls["_o9vT82YVEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_C07EFA49.html"];
contentPage.processPage.elementUrls["_irjgMWPQEemIdoc4rfIcVg"] = ["Pre-Production","Game Development Process/deliveryprocesses/Pre-Production_8F5CC1A7.html"];
contentPage.processPage.elementUrls["_C___IGYaEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_F0C13CC.html"];
contentPage.processPage.elementUrls["_CNBKYGYXEemzSZdddslyvQ"] = ["Implement All Game States","Game Development Process/deliveryprocesses/implement_all_game_states_AA6400B.html"];
contentPage.processPage.elementUrls["_C_54hGYaEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_508ADE8C.html"];
contentPage.processPage.elementUrls["_InGNsGYeEemzSZdddslyvQ"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_3B050176.html"];
contentPage.processPage.elementUrls["_FSPKtGYeEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_D3953331.html"];
contentPage.processPage.elementUrls["_Hd0KQWPVEemIdoc4rfIcVg"] = ["Perform Project Postmortem","Game Development Process/deliveryprocesses/Perform Project Postmortem_62059F39.html"];
contentPage.processPage.elementUrls["_xKJQjWYcEemzSZdddslyvQ"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_C25374DB.html"];
contentPage.processPage.elementUrls["_Nisug2buEemO0uSCmyE9oA"] = ["Developer","Game Development Process/deliveryprocesses/developer_B3B5163.html"];
contentPage.processPage.elementUrls["_aIfIN2YbEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_F920EE22.html"];
contentPage.processPage.elementUrls["_xKIpcWYcEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_62564602.html"];
contentPage.processPage.elementUrls["_fXlnIGYXEemzSZdddslyvQ"] = ["Create Screenshots and Demo Videos","Game Development Process/deliveryprocesses/create_screenshots_and_demo_videos_C2A2C1DB.html"];
contentPage.processPage.elementUrls["__kzyAGYWEemzSZdddslyvQ"] = ["Implement Game View","Game Development Process/deliveryprocesses/implement_game_view_7165159.html"];
contentPage.processPage.elementUrls["_6iRvcWYaEemzSZdddslyvQ"] = ["Game Assets","Game Development Process/deliveryprocesses/game_assets_70C0ED7D.html"];
contentPage.processPage.elementUrls["_xLQnoWYYEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_C4ED9DE3.html"];
contentPage.processPage.elementUrls["_FSIdCmYeEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_ED168EA8.html"];
contentPage.processPage.elementUrls["_GoMYYWYbEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_84EA6565.html"];
contentPage.processPage.elementUrls["_xKNiAGYcEemzSZdddslyvQ"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_22D8E168.html"];
contentPage.processPage.elementUrls["_6OUcNGYbEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_CBBE3DD3.html"];
contentPage.processPage.elementUrls["_yuU2o2b5EemO0uSCmyE9oA"] = ["Source Code","Game Development Process/deliveryprocesses/source_code_F002F837.html"];
contentPage.processPage.elementUrls["_NisuhWbuEemO0uSCmyE9oA"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_785A49A7.html"];
contentPage.processPage.elementUrls["_xLppNGYYEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_B6F50D7.html"];
contentPage.processPage.elementUrls["_SurXIWYdEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_3617326B.html"];
contentPage.processPage.elementUrls["_yuU2oGb5EemO0uSCmyE9oA"] = ["Implement All Game States","Game Development Process/deliveryprocesses/implement_all_game_states_8DF22E4C.html"];
contentPage.processPage.elementUrls["_kCE9QGb8EemO0uSCmyE9oA"] = ["Project Postmortem","Game Development Process/deliveryprocesses/project_postmortem_E6C70BE0.html"];
contentPage.processPage.elementUrls["_6iSWg2YaEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_DA7B5FD4.html"];
contentPage.processPage.elementUrls["_0M-7FGb7EemO0uSCmyE9oA"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_454DA245.html"];
contentPage.processPage.elementUrls["_ZD0-sWPVEemIdoc4rfIcVg"] = ["Perform Game Demo","Game Development Process/deliveryprocesses/Perform Game Demo_45B6A1C7.html"];
contentPage.processPage.elementUrls["_xNhncGeXEemt_6qJODnYDA"] = ["External Tool","Game Development Process/deliveryprocesses/external_tool_82476666.html"];
contentPage.processPage.elementUrls["_On0ToGYWEemzSZdddslyvQ"] = ["Create Plan and Schedule","Game Development Process/deliveryprocesses/create_plan_and_schedule_68541123.html"];
contentPage.processPage.elementUrls["_j4oMkWYbEemzSZdddslyvQ"] = ["State Diagram","Game Development Process/deliveryprocesses/state_diagram_F3B61E27.html"];
contentPage.processPage.elementUrls["_0NIsFGb7EemO0uSCmyE9oA"] = ["UI Mockups","Game Development Process/deliveryprocesses/ui_mockups_DB88F366.html"];
contentPage.processPage.elementUrls["_FSJEFWYeEemzSZdddslyvQ"] = ["Professor","Game Development Process/deliveryprocesses/professor_4C3320EF.html"];
contentPage.processPage.elementUrls["__05_gWPREemIdoc4rfIcVg"] = ["Identify and Refine Game Art and Interface","Game Development Process/deliveryprocesses/Identify and Refine Game Art and Interface_FD8C1DE3.html"];
contentPage.processPage.elementUrls["_xLQnpGYYEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_7EE19FF2.html"];
contentPage.processPage.elementUrls["_xKEYBGYcEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_E8141E20.html"];
contentPage.processPage.elementUrls["_dDRpEWPQEemIdoc4rfIcVg"] = ["Game Development Process","Game Development Process/deliveryprocesses/Game Development Process_A864547.html"];
contentPage.processPage.elementUrls["_NPLrvWblEemO0uSCmyE9oA"] = ["Developer","Game Development Process/deliveryprocesses/developer_220723BB.html"];
contentPage.processPage.elementUrls["_FSIdDWYeEemzSZdddslyvQ"] = ["Game","Game Development Process/deliveryprocesses/game_C30F5CB1.html"];
contentPage.processPage.elementUrls["_-I2JgGPVEemIdoc4rfIcVg"] = ["Milestone 1","Game Development Process/deliveryprocesses/Milestone 1_B94DE570.html"];
contentPage.processPage.elementUrls["_B1NGgGPWEemIdoc4rfIcVg"] = ["Milestone 3","Game Development Process/deliveryprocesses/Milestone 3_DA7EE7C5.html"];
contentPage.processPage.elementUrls["_j4fpsWYbEemzSZdddslyvQ"] = ["Object Oriented Design","Game Development Process/deliveryprocesses/object_oriented_design_11E0032B.html"];
contentPage.processPage.elementUrls["_-TgMSmPTEemIdoc4rfIcVg"] = ["Plan and Schedule","Game Development Process/deliveryprocesses/Plan Production_8B7B6E21.html"];
contentPage.processPage.elementUrls["_FR_TEWYeEemzSZdddslyvQ"] = ["Source Code","Game Development Process/deliveryprocesses/source_code_884A9969.html"];
contentPage.processPage.elementUrls["_0M-7E2b7EemO0uSCmyE9oA"] = ["Game Concept","Game Development Process/deliveryprocesses/game_concept_E2CC8A11.html"];
contentPage.processPage.elementUrls["_fl8BoGYWEemzSZdddslyvQ"] = ["Create Release Tag","Game Development Process/deliveryprocesses/create_release_tag_2C39BDD0.html"];
contentPage.processPage.elementUrls["_FSJEEmYeEemzSZdddslyvQ"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_763A52E6.html"];
contentPage.processPage.elementUrls["_SCLoEWYeEemzSZdddslyvQ"] = ["Test Reults","Game Development Process/deliveryprocesses/test_reults_2014173B.html"];
contentPage.processPage.elementUrls["_Z4oEEGYXEemzSZdddslyvQ"] = ["Perform Project Postmortem","Game Development Process/deliveryprocesses/perform_project_postmortem_632FCEFB.html"];
contentPage.processPage.elementUrls["_aIfIMWYbEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_DD1C2228.html"];
contentPage.processPage.elementUrls["_PMIhoGYWEemzSZdddslyvQ"] = ["Create Presentations","Game Development Process/deliveryprocesses/create_presentation_FF3FB87C.html"];
contentPage.processPage.elementUrls["_xKEYE2YcEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_97DA8E68.html"];
contentPage.processPage.elementUrls["_xKJQh2YcEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_90A29A78.html"];
contentPage.processPage.elementUrls["_0NIsEmb7EemO0uSCmyE9oA"] = ["Project Plan and Schedule","Game Development Process/deliveryprocesses/project_plan_and_schedule_102E056D.html"];
contentPage.processPage.elementUrls["_yuU2qWb5EemO0uSCmyE9oA"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_21B3D29A.html"];
contentPage.processPage.elementUrls["_63FUEGYVEemzSZdddslyvQ"] = ["Create and Update Meeting Logs","Game Development Process/deliveryprocesses/create_and_update_meeting_logs_79CC8D75.html"];
contentPage.processPage.elementUrls["_6iSWgGYaEemzSZdddslyvQ"] = ["Game Concept","Game Development Process/deliveryprocesses/game_concept_786A95E9.html"];
contentPage.processPage.elementUrls["_COWKoGYYEemzSZdddslyvQ"] = ["Create and Update Game Assets","Game Development Process/deliveryprocesses/create_and_update_game_assets_55EAA442.html"];
contentPage.processPage.elementUrls["_6iSWhmYaEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_36336C2E.html"];
contentPage.processPage.elementUrls["_C___I2YaEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_711CDDB7.html"];
contentPage.processPage.elementUrls["__41vBGYbEemzSZdddslyvQ"] = ["Meeting Log","Game Development Process/deliveryprocesses/meeting_log_7D13BF32.html"];
contentPage.processPage.elementUrls["_hKFU8GYWEemzSZdddslyvQ"] = ["Create Screenshots and Demo Videos","Game Development Process/deliveryprocesses/create_screenshots_and_demo_videos_4CB4F349.html"];
contentPage.processPage.elementUrls["_ESebAGYXEemzSZdddslyvQ"] = ["Perform Test","Game Development Process/deliveryprocesses/perform_test_E70653A.html"];
contentPage.processPage.elementUrls["_0M-7EGb7EemO0uSCmyE9oA"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_80BBC026.html"];
contentPage.processPage.elementUrls["_nKphgWYcEemzSZdddslyvQ"] = ["Code Repository","Game Development Process/deliveryprocesses/code_repository_FB91EB9.html"];
contentPage.processPage.elementUrls["_hyAW8WYeEemzSZdddslyvQ"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_99FA53BC.html"];
contentPage.processPage.elementUrls["_InGNtGYeEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_FF96E395.html"];
contentPage.processPage.elementUrls["_Rg-5IGYWEemzSZdddslyvQ"] = ["Create Presentations","Game Development Process/deliveryprocesses/create_presentation_D787A063.html"];
contentPage.processPage.elementUrls["_6OUcN2YbEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_2DCF07BE.html"];
contentPage.processPage.elementUrls["_wwch0WPREemIdoc4rfIcVg"] = ["Identify and Refine Game Design","Game Development Process/deliveryprocesses/Identify and Refine Game Design_B73C13C4.html"];
contentPage.processPage.elementUrls["__41vAWYbEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_C31FBD23.html"];
contentPage.processPage.elementUrls["_FSPKwGYeEemzSZdddslyvQ"] = ["Presentation","Game Development Process/deliveryprocesses/presentation_214AD98E.html"];
contentPage.processPage.elementUrls["_FSMucWYeEemzSZdddslyvQ"] = ["Test Plan","Game Development Process/deliveryprocesses/test_plan_D79195BF.html"];
contentPage.processPage.elementUrls["_xKEYCmYcEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_A5DCF465.html"];
contentPage.processPage.elementUrls["_C_6fkWYaEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_BBC7530A.html"];
contentPage.processPage.elementUrls["_InFmoGYeEemzSZdddslyvQ"] = ["Create Test Plan","Game Development Process/deliveryprocesses/create_test_plan_28BD78FA.html"];
contentPage.processPage.elementUrls["_xKIpemYcEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_DA131E56.html"];
contentPage.processPage.elementUrls["_xKNh92YcEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_92B0389A.html"];
contentPage.processPage.elementUrls["_aIcr9GYbEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_B07CBC78.html"];
contentPage.processPage.elementUrls["_xKEYFmYcEemzSZdddslyvQ"] = ["Project Plan and Schedule","Game Development Process/deliveryprocesses/project_plan_and_schedule_F3929AC2.html"];
contentPage.processPage.elementUrls["_FSIdBGYeEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_2F4DB863.html"];
contentPage.processPage.elementUrls["_yuU2oWb5EemO0uSCmyE9oA"] = ["Developer","Game Development Process/deliveryprocesses/developer_98900E5C.html"];
contentPage.processPage.elementUrls["_-TgMRGPTEemIdoc4rfIcVg"] = ["Identify and Refine Game Design","Game Development Process/deliveryprocesses/Identify and Refine Game Design_CDB297DC.html"];
contentPage.processPage.elementUrls["_j4jUEWYbEemzSZdddslyvQ"] = ["State Diagram","Game Development Process/deliveryprocesses/state_diagram_AD386BBA.html"];
contentPage.processPage.elementUrls["_CLB_UGd1Eem5JZDxFflhnw"] = ["Create and Update Game Assets","Game Development Process/deliveryprocesses/create_and_update_game_assets_2B08D095.html"];
contentPage.processPage.elementUrls["_yw_EwGYXEemzSZdddslyvQ"] = ["Create and Update State Diagram","Game Development Process/deliveryprocesses/create_and_update_state_diagram_E3CA6D1D.html"];
contentPage.processPage.elementUrls["_xKM65GYcEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_B6EF822.html"];
contentPage.processPage.elementUrls["_0NIsE2b7EemO0uSCmyE9oA"] = ["State Diagram","Game Development Process/deliveryprocesses/state_diagram_7907DB32.html"];
contentPage.processPage.elementUrls["_6-IWcmPUEemIdoc4rfIcVg"] = ["Testing","Game Development Process/deliveryprocesses/Testing_E18BD5AA.html"];
contentPage.processPage.elementUrls["_xKNh8WYcEemzSZdddslyvQ"] = ["Tester","Game Development Process/deliveryprocesses/tester_76AB6CA0.html"];
contentPage.processPage.elementUrls["_dqIbcmPVEemIdoc4rfIcVg"] = ["Perform Game Demo","Game Development Process/deliveryprocesses/Perform Game Demo_9662320C.html"];
contentPage.processPage.elementUrls["_xKEYB2YcEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_4A24E80B.html"];
contentPage.processPage.elementUrls["_FSIdAWYeEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_7559B654.html"];
contentPage.processPage.elementUrls["_6OUcMWYbEemzSZdddslyvQ"] = ["Artist","Game Development Process/deliveryprocesses/artist_11CA3BC4.html"];
contentPage.processPage.elementUrls["_-WOUcGYVEemzSZdddslyvQ"] = ["Create and Update Class Diagram","Game Development Process/deliveryprocesses/create_and_update_class_diagram_B2648CFB.html"];
contentPage.processPage.elementUrls["_xKIpdGYcEemzSZdddslyvQ"] = ["Developer","Game Development Process/deliveryprocesses/developer_1C4A4811.html"];
contentPage.processPage.elementUrls["_sogRgWPQEemIdoc4rfIcVg"] = ["Post-Production","Game Development Process/deliveryprocesses/Post-Production_BBC9A8E.html"];
contentPage.processPage.elementUrls["_NPLrsWblEemO0uSCmyE9oA"] = ["Developer","Game Development Process/deliveryprocesses/developer_D4517D5E.html"];
contentPage.processPage.elementUrls["_xKEYEGYcEemzSZdddslyvQ"] = ["Art and Interface Document","Game Development Process/deliveryprocesses/art_and_interface_document_35C9C47D.html"];
contentPage.processPage.elementUrls["_NwEkkWYcEemzSZdddslyvQ"] = ["Project Plan and Schedule","Game Development Process/deliveryprocesses/project_plan_and_schedule_FC63A8CF.html"];
contentPage.processPage.elementUrls["_kCHZgGb8EemO0uSCmyE9oA"] = ["Readme file","Game Development Process/deliveryprocesses/readme_file_52C9788.html"];
contentPage.processPage.elementUrls["_kB5-IGb8EemO0uSCmyE9oA"] = ["Code Repository","Game Development Process/deliveryprocesses/code_repository_97850A6B.html"];
contentPage.processPage.elementUrls["_xKM652YcEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_6D7FC20D.html"];
contentPage.processPage.elementUrls["_KQTrYGYXEemzSZdddslyvQ"] = ["Fix Defects","Game Development Process/deliveryprocesses/fix_defects_2F4EC9B.html"];
contentPage.processPage.elementUrls["_NisugGbuEemO0uSCmyE9oA"] = ["Establish Game Concept","Game Development Process/deliveryprocesses/establish_game_concept_A92A8778.html"];
contentPage.processPage.elementUrls["_C_54h2YaEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_B29BA877.html"];
contentPage.processPage.elementUrls["_vUoSoGYXEemzSZdddslyvQ"] = ["Create and Update Class Diagram","Game Development Process/deliveryprocesses/create_and_update_class_diagram_38C84FA4.html"];
contentPage.processPage.elementUrls["_xKJQgWYcEemzSZdddslyvQ"] = ["Architecture Document","Game Development Process/deliveryprocesses/architecture_document_749DCE7E.html"];
contentPage.processPage.elementUrls["_iC2MI2YaEemzSZdddslyvQ"] = ["Game design Document","Game Development Process/deliveryprocesses/game_design_document_DACE28F0.html"];
contentPage.processPage.elementUrls["_7lIs4GYVEemzSZdddslyvQ"] = ["Create and Update Meeting Logs","Game Development Process/deliveryprocesses/create_and_update_meeting_logs_918DE579.html"];
contentPage.processPage.elementUrls["_C___JmYaEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_CCD4EA11.html"];
contentPage.processPage.elementUrls["_kCJ1wWb8EemO0uSCmyE9oA"] = ["Source Code","Game Development Process/deliveryprocesses/source_code_37E29E5D.html"];
contentPage.processPage.elementUrls["_kCJ1wGb8EemO0uSCmyE9oA"] = ["Release Notes","Game Development Process/deliveryprocesses/release_notes_2D44BE4D.html"];
contentPage.processPage.elementUrls["_3kOq0GeXEemt_6qJODnYDA"] = ["Develop External Tool","Game Development Process/deliveryprocesses/develop_external_tool_4EB112F7.html"];
contentPage.processPage.elementUrls["_FSPKt2YeEemzSZdddslyvQ"] = ["Project Coordinator","Game Development Process/deliveryprocesses/project_coordinator_35A5FD1C.html"];
